sonar.projectKey=aitboutargantefatimazohra_oeildirect
# Chemins des sources (ne jamais mettre SONAR_TOKEN ici — uniquement $env:SONAR_TOKEN sous PowerShell)
sonar.sources=front,backend
sonar.token=e886d3a315258a6f3b8ab4ef704ae8c27f1d586a
sonar.sourceEncoding=UTF-8
sonar.java.binaries=backend/build/classes/java/main,backend/build/classes/java/test
sonar.coverage.jacoco.xmlReportPaths=backend/build/reports/jacoco/test/jacocoTestReport.xml
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/build/**,**/.scannerwork/**,**/out/**,**/coverage/**,**/*.min.js,backend/src/test/**
sonar.tests=backend/src/test/java
# On n'a pas encore de coverage JS/TS, sinon l'overall coverage chute.
sonar.coverage.exclusions=front/**,**/*.js,**/*.jsx,**/*.ts,**/*.tsx
sonar.host.url=https://sonarcloud.io
sonar.organization=aitboutargantefatimazohra