sonar.projectKey=ahmedbenidar_testsonar
sonar.sources=.
sonar.token=2dbf3c5342116443529a2284d11334e5f40a25fa
sonar.sourceEncoding=UTF-8
sonar.java.binaries=backend/build/classes/java/main,backend/build/classes/java/test
sonar.coverage.jacoco.xmlReportPaths=backend/build/reports/jacoco/test/jacocoTestReport.xml
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/build/**,**/.scannerwork/**,**/out/**,**/coverage/**,**/*.min.js,backend/src/test/**
sonar.tests=backend/src/test/java
# On n'a pas encore de coverage JS/TS, sinon l'overall coverage chute.
sonar.coverage.exclusions=front/**,**/*.js,**/*.jsx,**/*.ts,**/*.tsx
sonar.host.url=https://sonarcloud.io
sonar.organization=ahmedbenidar